# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oplus/euicc/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oplus/euicc

PRODUCT_COPY_FILES += \
    vendor/oplus/euicc/proprietary/odm/bin/hw/vendor.oplus.hardware.esim@1.0-service:$(TARGET_COPY_OUT_ODM)/bin/hw/vendor.oplus.hardware.esim@1.0-service \
    vendor/oplus/euicc/proprietary/odm/etc/init/esim@1.0-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/esim@1.0-service.rc \
    vendor/oplus/euicc/proprietary/odm/lib/vendor.oplus.hardware.esim-V1-ndk.so:$(TARGET_COPY_OUT_ODM)/lib/vendor.oplus.hardware.esim-V1-ndk.so \
    vendor/oplus/euicc/proprietary/odm/lib64/vendor.oplus.hardware.esim-V1-ndk.so:$(TARGET_COPY_OUT_ODM)/lib64/vendor.oplus.hardware.esim-V1-ndk.so \
    vendor/oplus/euicc/proprietary/system_ext/etc/permissions/euicc_features.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/euicc_features.xml \
    vendor/oplus/euicc/proprietary/system_ext/etc/permissions/euicc_permission.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/euicc_permission.xml

PRODUCT_PACKAGES += \
    EuiccGoogle \
    manifest_oplus_esim
